# Cleaning up the Titanic Dataset

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\MR.OKECH\Desktop\Joshua\Data Career\Matering Python for DA\Titanic Dataset\Titanic-Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
df.shape

(891, 12)

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
df.duplicated().sum()

0

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
df['Age'].mean()

29.69911764705882

In [9]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [10]:
df['Age'] = df['Age'].round(1)

In [11]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.7,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [12]:
df[['Last name', 'Rest']] = df['Name'].str.split(', ', expand = True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last name,Rest
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Montvila,Rev. Juozas
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss. Margaret Edith
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.7,1,2,W./C. 6607,23.4500,NaN,S,Johnston,"Miss. Catherine Helen ""Carrie"""
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr. Karl Howell
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Dooley,Mr. Patrick

In [13]:
df[['Title', 'First_Middle_Nmaes']] = df['Rest'].str.split(' ', n=1, expand = True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last name,Rest,Title,First_Middle_Nmaes
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,Miss.,Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),Mrs.,Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,Mr.,William Henry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Montvila,Rev. Juozas,Rev.,Juozas
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss. Margaret Edith,Miss.,Margaret Edith
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.7,1,2,W./C. 6607,23.4500,NaN,S,Johnston,"Miss. Catherine Helen ""Carrie""",Miss.,"Catherine Helen ""Carrie"""
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr. Karl Howell,Mr.,Karl Howell
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Dooley,Mr. Patrick,Mr.,Patrick

In [14]:
df.drop(columns = ['Name', 'Rest'], inplace = True)
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last name,Title,First_Middle_Nmaes
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
3,4,1,1,female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel)
4,5,0,3,male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr.,William Henry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,211536,13.0000,NaN,S,Montvila,Rev.,Juozas
887,888,1,1,female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss.,Margaret Edith
888,889,0,3,female,29.7,1,2,W./C. 6607,23.4500,NaN,S,Johnston,Miss.,"Catherine Helen ""Carrie"""
889,890,1,1,male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr.,Karl Howell
890,891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q,Dooley,Mr.,Patrick

In [15]:
df['Sex'] = df['Sex'].str.replace('male', 'Male')
df['Sex'] = df['Sex'].str.replace('feMale', 'Female')

df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last name,Title,First_Middle_Nmaes
0,1,0,3,Male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,Female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,Female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
3,4,1,1,Female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel)
4,5,0,3,Male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr.,William Henry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Male,27.0,0,0,211536,13.0000,NaN,S,Montvila,Rev.,Juozas
887,888,1,1,Female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss.,Margaret Edith
888,889,0,3,Female,29.7,1,2,W./C. 6607,23.4500,NaN,S,Johnston,Miss.,"Catherine Helen ""Carrie"""
889,890,1,1,Male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr.,Karl Howell
890,891,0,3,Male,32.0,0,0,370376,7.7500,NaN,Q,Dooley,Mr.,Patrick

In [16]:
df['Cabin'] = df['Cabin'].fillna('')
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last name,Title,First_Middle_Nmaes
0,1,0,3,Male,22.0,1,0,A/5 21171,7.2500,,S,Braund,Mr.,Owen Harris
1,2,1,1,Female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,Female,26.0,0,0,STON/O2. 3101282,7.9250,,S,Heikkinen,Miss.,Laina
3,4,1,1,Female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel)
4,5,0,3,Male,35.0,0,0,373450,8.0500,,S,Allen,Mr.,William Henry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Male,27.0,0,0,211536,13.0000,,S,Montvila,Rev.,Juozas
887,888,1,1,Female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss.,Margaret Edith
888,889,0,3,Female,29.7,1,2,W./C. 6607,23.4500,,S,Johnston,Miss.,"Catherine Helen ""Carrie"""
889,890,1,1,Male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr.,Karl Howell
890,891,0,3,Male,32.0,0,0,370376,7.7500,,Q,Dooley,Mr.,Patrick

In [17]:
df[['First Name', 'Middle_Nmaes']] = df['First_Middle_Nmaes'].str.split(' ', n=1, expand = True)
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last name,Title,First_Middle_Nmaes,First Name,Middle_Nmaes
0,1,0,3,Male,22.0,1,0,A/5 21171,7.2500,,S,Braund,Mr.,Owen Harris,Owen,Harris
1,2,1,1,Female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer),John,Bradley (Florence Briggs Thayer)
2,3,1,3,Female,26.0,0,0,STON/O2. 3101282,7.9250,,S,Heikkinen,Miss.,Laina,Laina,None
3,4,1,1,Female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel),Jacques,Heath (Lily May Peel)
4,5,0,3,Male,35.0,0,0,373450,8.0500,,S,Allen,Mr.,William Henry,William,Henry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Male,27.0,0,0,211536,13.0000,,S,Montvila,Rev.,Juozas,Juozas,None
887,888,1,1,Female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss.,Margaret Edith,Margaret,Edith
888,889,0,3,Female,29.7,1,2,W./C. 6607,23.4500,,S,Johnston,Miss.,"Catherine Helen ""Carrie""",Catherine,"Helen ""Carrie"""
889,890,1,1,Male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr.,Karl Howell,Karl,Howell
890,891,0,3,Male,32.0,0,0,370376,7.7500,,Q,Dooley,Mr.,Patrick,Patrick,None

In [18]:
df[['Middle Name', 'Other Name9s0']] = df['Middle_Nmaes'].str.split(' ', n=1, expand = True)
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last name,Title,First_Middle_Nmaes,First Name,Middle_Nmaes,Middle Name,Other Name9s0
0,1,0,3,Male,22.0,1,0,A/5 21171,7.2500,,S,Braund,Mr.,Owen Harris,Owen,Harris,Harris,None
1,2,1,1,Female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer),John,Bradley (Florence Briggs Thayer),Bradley,(Florence Briggs Thayer)
2,3,1,3,Female,26.0,0,0,STON/O2. 3101282,7.9250,,S,Heikkinen,Miss.,Laina,Laina,None,None,None
3,4,1,1,Female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel),Jacques,Heath (Lily May Peel),Heath,(Lily May Peel)
4,5,0,3,Male,35.0,0,0,373450,8.0500,,S,Allen,Mr.,William Henry,William,Henry,Henry,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Male,27.0,0,0,211536,13.0000,,S,Montvila,Rev.,Juozas,Juozas,None,None,None
887,888,1,1,Female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss.,Margaret Edith,Margaret,Edith,Edith,None
888,889,0,3,Female,29.7,1,2,W./C. 6607,23.4500,,S,Johnston,Miss.,"Catherine Helen ""Carrie""",Catherine,"Helen ""Carrie""",Helen,"""Carrie"""
889,890,1,1,Male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr.,Karl Howell,Karl,Howell,Howell,None
890,891,0,3,Male,32.0,0,0,370376,7.7500,,Q,Dooley,Mr.,Patrick,Patrick,None,None,None

In [19]:
df.drop(columns = ['First_Middle_Nmaes', 'Middle_Nmaes'], inplace = True)
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last name,Title,First Name,Middle Name,Other Name9s0
0,1,0,3,Male,22.0,1,0,A/5 21171,7.2500,,S,Braund,Mr.,Owen,Harris,None
1,2,1,1,Female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John,Bradley,(Florence Briggs Thayer)
2,3,1,3,Female,26.0,0,0,STON/O2. 3101282,7.9250,,S,Heikkinen,Miss.,Laina,None,None
3,4,1,1,Female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques,Heath,(Lily May Peel)
4,5,0,3,Male,35.0,0,0,373450,8.0500,,S,Allen,Mr.,William,Henry,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Male,27.0,0,0,211536,13.0000,,S,Montvila,Rev.,Juozas,None,None
887,888,1,1,Female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss.,Margaret,Edith,None
888,889,0,3,Female,29.7,1,2,W./C. 6607,23.4500,,S,Johnston,Miss.,Catherine,Helen,"""Carrie"""
889,890,1,1,Male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr.,Karl,Howell,None
890,891,0,3,Male,32.0,0,0,370376,7.7500,,Q,Dooley,Mr.,Patrick,None,None

In [20]:
# New column order
new_column_order = ['PassengerId', 'Survived', 'Pclass', 'Title', 'First Name', 'Middle Name', 'Last name', 'Other Name9s0', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

df = df[new_column_order]
df

,PassengerId,Survived,Pclass,Title,First Name,Middle Name,Last name,Other Name9s0,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Mr.,Owen,Harris,Braund,None,Male,22.0,1,0,A/5 21171,7.2500,,S
1,2,1,1,Mrs.,John,Bradley,Cumings,(Florence Briggs Thayer),Female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Miss.,Laina,None,Heikkinen,None,Female,26.0,0,0,STON/O2. 3101282,7.9250,,S
3,4,1,1,Mrs.,Jacques,Heath,Futrelle,(Lily May Peel),Female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Mr.,William,Henry,Allen,None,Male,35.0,0,0,373450,8.0500,,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Rev.,Juozas,None,Montvila,None,Male,27.0,0,0,211536,13.0000,,S
887,888,1,1,Miss.,Margaret,Edith,Graham,None,Female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,Miss.,Catherine,Helen,Johnston,"""Carrie""",Female,29.7,1,2,W./C. 6607,23.4500,,S
889,890,1,1,Mr.,Karl,Howell,Behr,None,Male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,Mr.,Patrick,None,Dooley,None,Male,32.0,0,0,370376,7.7500,,Q

In [21]:
df = df.rename(columns = {'First Name': 'FirstName', 'Middle Name': 'MiddleName', 'Last name': 'LastName', 'Other Name9s0': 'OtherName(s)'})
df

,PassengerId,Survived,Pclass,Title,FirstName,MiddleName,LastName,OtherName(s),Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Mr.,Owen,Harris,Braund,None,Male,22.0,1,0,A/5 21171,7.2500,,S
1,2,1,1,Mrs.,John,Bradley,Cumings,(Florence Briggs Thayer),Female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Miss.,Laina,None,Heikkinen,None,Female,26.0,0,0,STON/O2. 3101282,7.9250,,S
3,4,1,1,Mrs.,Jacques,Heath,Futrelle,(Lily May Peel),Female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Mr.,William,Henry,Allen,None,Male,35.0,0,0,373450,8.0500,,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Rev.,Juozas,None,Montvila,None,Male,27.0,0,0,211536,13.0000,,S
887,888,1,1,Miss.,Margaret,Edith,Graham,None,Female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,Miss.,Catherine,Helen,Johnston,"""Carrie""",Female,29.7,1,2,W./C. 6607,23.4500,,S
889,890,1,1,Mr.,Karl,Howell,Behr,None,Male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,Mr.,Patrick,None,Dooley,None,Male,32.0,0,0,370376,7.7500,,Q

In [22]:
df['OtherName(s)'] = df['OtherName(s)'].str.replace(r'[^a-zA-Z\s]', '', regex=True)
df

,PassengerId,Survived,Pclass,Title,FirstName,MiddleName,LastName,OtherName(s),Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Mr.,Owen,Harris,Braund,None,Male,22.0,1,0,A/5 21171,7.2500,,S
1,2,1,1,Mrs.,John,Bradley,Cumings,Florence Briggs Thayer,Female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Miss.,Laina,None,Heikkinen,None,Female,26.0,0,0,STON/O2. 3101282,7.9250,,S
3,4,1,1,Mrs.,Jacques,Heath,Futrelle,Lily May Peel,Female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Mr.,William,Henry,Allen,None,Male,35.0,0,0,373450,8.0500,,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Rev.,Juozas,None,Montvila,None,Male,27.0,0,0,211536,13.0000,,S
887,888,1,1,Miss.,Margaret,Edith,Graham,None,Female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,Miss.,Catherine,Helen,Johnston,Carrie,Female,29.7,1,2,W./C. 6607,23.4500,,S
889,890,1,1,Mr.,Karl,Howell,Behr,None,Male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,Mr.,Patrick,None,Dooley,None,Male,32.0,0,0,370376,7.7500,,Q